#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99

PROG=/usr/bin/holder

start_service() {
    procd_open_instance "system-holder"
    procd_set_param command "$PROG"
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

